version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: product-services
    restart: always
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: product
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/products
volumes:
  postgres_data:
