version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: user-services
    restart: always
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/users
volumes:
  postgres_data:
